[package]
name = "lasker"
version = "0.1.0"
authors = ["thomas <tduffy000@citymail.cuny.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
